### ISSUE TITLE
Unable to push commits/origin 

### ISSUE THREAD

**Issue by Amy-Stalter** [Amy-Stalter/horizontal-nav#1]
@thomasjbradley
Github app gives an authentication error, I have looked into common reasons and it still will not let me.

Thanks.

**Comment by thomasjbradley** [comment]
Go into GitHub Desktop. In the menu, go to `Repository > Repository Settings`.

Send me a screenshot of that screen.

**Comment by Amy-Stalter** [comment]
![screencapture-github-Amy-Stalter-horizontal-nav-settings-2019-10-24-13_46_31](https://user-images.githubusercontent.com/55193282/67511413-d7d90f80-f664-11e9-99f6-69a5669a482a.png)

@thomasjbradley

**Comment by thomasjbradley** [comment]
GitHub Desktop application on your computer—not GitHub website.

**Comment by Amy-Stalter** [comment]
![UNADJUSTEDNONRAW_thumb_b](https://user-images.githubusercontent.com/55193282/67511744-8715e680-f665-11e9-96c7-bb21e94a275b.jpg)

**Comment by thomasjbradley** [comment]
![67511744-8715e680-f665-11e9-96c7-bb21e94a275b](https://user-images.githubusercontent.com/105192/67511850-b3316780-f665-11e9-8fe9-2b4bf374a43e.jpg)

In the URL that’s there, change my username, `acgd-webdev-1` part, to your username: `Amy-Stalter` & save.

**Comment by Amy-Stalter** [comment]
![UNADJUSTEDNONRAW_thumb_c](https://user-images.githubusercontent.com/55193282/67512668-53d45700-f667-11e9-91b6-2f948db6171f.jpg)

like this? if so, it says that it no longer exists. 
@thomasjbradley

**Comment by thomasjbradley** [comment]
Just your username, none of the `-webdev-1` part—that’s still part of my username.

**Comment by Amy-Stalter** [comment]
@thomasjbradley 
That fixed it thank you
